### ISSUE TITLE
Theme not applying to GTK apps

### ISSUE THREAD

**Issue by Anirudh-K96** [end-4/dots-hyprland#1259]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/i-i/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

```
<!-- Run `./diagnose` inside the repo, and paste the result here! -->
```

</details>

### Step 3. Describe the issue

I had the GTK themes working for a couple of days after I installed this config but they suddenly stopped working. I don't know how to get them back. Please tell me if I should provide logs and where I can find them.

![Image](https://github.com/user-attachments/assets/c74ac014-4107-4fb3-ae36-46dd64a6c404)

<details><summary>Logs</summary>

```
<!-- Put your log content here!-->
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by Satoxyan** [comment]
try to execute the shell script
`~/.config/ags/scripts/color_generation/switchwall.sh`

**Comment by Satoxyan** [comment]
> Executing the shell script in `~/.config/ags/scripts/color_generation/switchwall.sh` resulted in opening a Nautilus window which prompted me to select a wallpaper similar to the Super+Ctrl+T functionality. After I selected the wallpaper, the colourscheme changed successfully but the GTK apps remained the same.
> On the terminal through which I ran the shell script, it gave me this error:
> `PermissionError: [Errno 13] Permission denied: '/home/anirudh/.config/gtk-4.0/gtk.css'
> undefined`
> 
> I'm not really sure how to fix this... please help me out

Try to `chmod 755` all the files inside `~/.config/gtk-4.0`, or even `chown` all of it

**Comment by Anirudh-K96** [comment]
I did do that but that didn't seem to work. Running the script still gives me the same result....

**Comment by Satoxyan** [comment]
> I did do that but that didn't seem to work. Running the script still gives me the same result....

What's the results of `ls -l ~/.config/gtk-4.0`?

**Comment by Lazylllama** [comment]
Getting the exact same issue. 

**~/.config/gtk-4.0**
`-rwxr-xr-x 1 root lazyllama 730 May 13 21:52 gtk.css*`

<br>

**~/.config/ags/scripts/color_generation/switchwall.sh**
```bash
SVG colors have been updated and saved to /home/lazyllama/.config/Kvantum/MaterialAdw/MaterialAdw.svg!
Config colors updated successfully!
cp: cannot create regular file '/home/lazyllama/.config/gtk-4.0/gtk.css': Permission denied

undefined
undefined
```

**Comment by Lazylllama** [comment]
> Getting the exact same issue.
> 
> **~/.config/gtk-4.0** `-rwxr-xr-x 1 root lazyllama 730 May 13 21:52 gtk.css*`
> 
> 
> **~/.config/ags/scripts/color_generation/switchwall.sh**
> 
> SVG colors have been updated and saved to /home/lazyllama/.config/Kvantum/MaterialAdw/MaterialAdw.svg!
> Config colors updated successfully!
> cp: cannot create regular file '/home/lazyllama/.config/gtk-4.0/gtk.css': Permission denied
> 
> undefined
> undefined

Fixed this. Just `chown (your user) ~/.config/gtk-4.0` and `chown (your user) ~/.config/gtk-4.0/gtk.css` and it wont give an error for no permissions. GTK still looks ugly as shit.

![Image](https://github.com/user-attachments/assets/96676281-c9de-470b-b669-581f05012300)

**Comment by caffeine01** [comment]
you need to install https://aur.archlinux.org/packages/libadwaita-without-adwaita-git

**Comment by theawesomeyopro1** [comment]
finally found a fix, thank you so much guys

**Comment by nyxv3il** [comment]
> > Executing the shell script in `~/.config/ags/scripts/color_generation/switchwall.sh` resulted in opening a Nautilus window which prompted me to select a wallpaper similar to the Super+Ctrl+T functionality. After I selected the wallpaper, the colourscheme changed successfully but the GTK apps remained the same.
> > On the terminal through which I ran the shell script, it gave me this error:
> > `PermissionError: [Errno 13] Permission denied: '/home/anirudh/.config/gtk-4.0/gtk.css' undefined`
> > I'm not really sure how to fix this... please help me out
> 
> Try to `chmod 755` all the files inside `~/.config/gtk-4.0`, or even `chown` all of it

I had the same issue and chown ing ~/.config/gtk-4.0/gtk.css fixed it for me. thank you so much.

**Comment by UcraNerd** [comment]
I still have this bug with gtk4 and if I chown then the theme becomes broken. I think that the matugen's gtk.css template is kinda broken right now...
