### ISSUE TITLE
Screenshot tool does not work properly with monitor scaling

### ISSUE THREAD

**Issue by alllexey-dev** [end-4/dots-hyprland#1539]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

```
/========================\
| Checking git repo info |
\========================/

[===diagnose===] git remote get-url origin
https://github.com/end-4/dots-hyprland.git
[---SUCCESS---]

[===diagnose===] git rev-parse HEAD
abdfd174825b315563b30632dde5bed1739dd1ab
[---SUCCESS---]

/=================\
| Checking distro |
\=================/

[===diagnose===] ii_check_distro
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
[---SUCCESS---]

/====================\
| Checking variables |
\====================/

[===diagnose===] declare -p XDG_CACHE_HOME
./diagnose: line 30: declare: XDG_CACHE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_CONFIG_HOME
./diagnose: line 30: declare: XDG_CONFIG_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_DATA_HOME
./diagnose: line 30: declare: XDG_DATA_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_STATE_HOME
./diagnose: line 30: declare: XDG_STATE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p ILLOGICAL_IMPULSE_VIRTUAL_ENV
declare -x ILLOGICAL_IMPULSE_VIRTUAL_ENV="~/.local/state/quickshell/.venv"
[---SUCCESS---]

/============================\
| Checking directories/files |
\============================/

[===diagnose===] ls -l /home/alllexey/.local/state/quickshell/.venv
total 16
-rw-r--r-- 1 alllexey alllexey   43 Jun 29 19:07 CACHEDIR.TAG
drwxr-xr-x 2 alllexey alllexey 4096 Jun 29 19:07 bin
drwxr-xr-x 3 alllexey alllexey 4096 Jun 29 19:07 lib
lrwxrwxrwx 1 alllexey alllexey    3 Jun 29 19:07 lib64 -> lib
-rw-r--r-- 1 alllexey alllexey  192 Jun 29 19:07 pyvenv.cfg
[---SUCCESS---]

/===================\
| Checking versions |
\===================/

[===diagnose===] Hyprland --version
Hyprland 0.49.0 built from branch main at commit ab900d8752af11ada256ea6fca54d5404587405c  (screencopy: fix improper box calculations for transforms (10870)).
Date: Sat Jun 28 23:01:14 2025
Tag: v0.49.0-133-gab900d875, commits: 6231
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.8.0
 hyprcursor 0.1.12
 hyprgraphics 0.1.4


no flags were set

[---SUCCESS---]
```

</details>

### Step 3. Describe the issue

I assume the screenshot is being taken without taking into account the current monitor scaling.
Same with window/layer highlighting.
See recording below. (1.5x scaling on my eDP-1, with 1x scaling everything is fine)

https://github.com/user-attachments/assets/ce81c3f0-6923-4ede-b08c-ff0d521e0834

<details><summary>Logs</summary>

```
Not needed I guess, should be reproducible
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by end-4** [comment]
did that fix it?

**Comment by alllexey-dev** [comment]
Now screenshots are taken as expected, window highlighting is fixed, but the "Content region" thing is still not where it should be.

https://github.com/user-attachments/assets/ce610c01-9117-4d83-917c-42fb29b3cbaa

**Comment by Bugraern** [comment]
![Image](https://github.com/user-attachments/assets/53c2238e-3983-4841-b486-97aab9c25749)

Same here + applications does not seem correct

**Comment by end-4** [comment]
try again guys

**Comment by Bugraern** [comment]
![Image](https://github.com/user-attachments/assets/6f831e84-d208-4ed2-b7f1-80869aa00316)

Content regions seems okey to me but as you can see the applications still does not work as expected. I figure that only the "upper side" of monitor applications  recognized. 

Another thing is applications no more clickable. Content regions works.


![Image](https://github.com/user-attachments/assets/779822dd-fc8a-4d13-975e-a8ec7a674c18)

If  look closely (sorry for my wide screenshot), you can see my mouse and it is selecting the kitty terminal instead of zen browser.

**Comment by Bugraern** [comment]
okay the screenshot has no mouse, the mouse is on zen browser's left side.

**Comment by end-4** [comment]
oh right, i updated the display of them but didn't update the click position calculation

**Comment by end-4** [comment]
uhh
maybe now?

**Comment by Bugraern** [comment]
![Image](https://github.com/user-attachments/assets/6b38b573-5494-477d-a21e-ee58fc994585)

Kinda okay on my main (right) screen except it misses some  applications but it totaly ignores the applications on my left screen. 

The click action is resolved. I can click the applications.

**Comment by Bugraern** [comment]
My screenshot problem is completely solved after the last commits.

**Comment by alllexey-dev** [comment]
Same but the "Content region" thing is still not there its expected to be (with monitor scaling).

In both examples, it selects the diagram more or less correctly, but on 1.5x it is shifted to the right and down.

(Also, how do I disable this thing? In my opinion, it's not very useful in most cases. Maybe introduce a config entry or something?)

https://github.com/user-attachments/assets/d69582dd-3d13-4ad1-93df-ada358feadf8

**Comment by ii7mood** [comment]
I am unsure if this should be its own issue but I encountered the same problem by setting the `QT_FONT_DPI` env variable.

I opted instead to configure the `QT_SCALE_FACTOR` variable in `~/.config/quickshell/ii/shell.qml` after reading the wiki.

https://github.com/user-attachments/assets/fc3ad3d5-f125-4592-b4b1-37337596ad3d
