### ISSUE TITLE
[Issue] Package 'gtksourceviewmm-3.0', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by os-guy** [end-4/dots-hyprland#955]
- Linux distro: Arch Linux

---
## The issue
I ran the installer script and when it started to build MicroTex, it gave me an output telling me that "gtksourceviewmm-3.0" is not found.

Here's the output Log:

```
-- We are working with GTK on a Unix like OS
-- Checking for module 'gtksourceviewmm-3.0'
--   Package 'gtksourceviewmm-3.0', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - gtksourceviewmm-3.0

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:215 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
```

I couldn't find any package which provides `gtksourceviewmm-3.0`.
Any info about this issue?

**Comment by MrSSHH** [comment]
Build  gtksourceviewmm-3.0 yourself, it should help

wget https://download.gnome.org/sources/gtksourceviewmm/3.0/gtksourceviewmm-3.0.0.tar.gz
tar -xvJf gtksourceviewmm-3.0.0.tar.xz
cd gtksourceviewmm-3.0.0
./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
sudo make install


then repeat in installer.

**Comment by os-guy** [comment]
> wget https://download.gnome.org/sources/gtksourceviewmm/3.0/gtksourceviewmm-3.0.0.tar.gz tar -xvJf gtksourceviewmm-3.0.0.tar.xz cd gtksourceviewmm-3.0.0 ./configure --prefix=/usr sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool make sudo make install

Thanks, it worked.
Do you know why this issue happened BTW?

**Comment by os-guy** [comment]
> > wget https://download.gnome.org/sources/gtksourceviewmm/3.0/gtksourceviewmm-3.0.0.tar.gz tar -xvJf gtksourceviewmm-3.0.0.tar.xz cd gtksourceviewmm-3.0.0 ./configure --prefix=/usr sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool make sudo make install
> 
> Thanks, it worked. Do you know why this issue happened BTW?

**Comment by ex-jandal** [comment]
i'm trying to build and it shows these errors:

```
checking for gtkmm-4.0 >= 3.18.0 gtksourceview-4 >= 3.99.0... no
configure: error: Package requirements (gtkmm-4.0 >= 3.18.0 gtksourceview-4 >= 3.99.0) were not met:

Package 'gtksourceview-4', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTKSOURCEVIEWMM_CFLAGS
and GTKSOURCEVIEWMM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Making all in gtksourceview/gtksourceviewmm
make[1]: Entering directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
make[1]: *** No rule to make target 'buffer.cc', needed by 'buffer.lo'.  Stop.
make[1]: Leaving directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
make: *** [Makefile:578: all-recursive] Error 1
Making install in gtksourceview/gtksourceviewmm
make[1]: Entering directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
make[1]: *** No rule to make target 'buffer.cc', needed by 'buffer.lo'.  Stop.
make[1]: Leaving directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
make: *** [Makefile:578: install-recursive] Error 1
```

**Comment by ex-jandal** [comment]
> i'm trying to build and it shows these errors:
> 
> ```
> Making all in gtksourceview/gtksourceviewmm
> make[1]: Entering directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
> make[1]: *** No rule to make target 'buffer.cc', needed by 'buffer.lo'.  Stop.
> make[1]: Leaving directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
> make: *** [Makefile:578: all-recursive] Error 1
> Making install in gtksourceview/gtksourceviewmm
> make[1]: Entering directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
> make[1]: *** No rule to make target 'buffer.cc', needed by 'buffer.lo'.  Stop.
> make[1]: Leaving directory '/home/abu_jandal/gtksourceviewmm/gtksourceview/gtksourceviewmm'
> make: *** [Makefile:578: install-recursive] Error 1
> ```

i figure it out:
you should download the dependents with this command:
```
sudo pacman -S gtkmm3 libtool autoconf automake pkgconf
```

**Comment by MrSSHH** [comment]
This one is on me, the line tar -xvJf gtksourceviewmm-3.0.0.tar.xz is the culprit I fixed it now it should be tar -xvJf gtksourceviewmm-3.0.0.tar.gz


Let me know if it works I'm not at home to check :)

**Comment by qualvey** [comment]
> Build gtksourceviewmm-3.0 yourself, it should help
> 
> wget https://download.gnome.org/sources/gtksourceviewmm/3.0/gtksourceviewmm-3.0.0.tar.gz tar -xvzf gtksourceviewmm-3.0.0.tar.gz cd gtksourcevbiewmm-3.0.0 ./configure --prefix=/usr sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool make sudo make install
> 
> then repeat in installer.

Cool,buddy.I was tryed build it from source code before .But I dont know this two step
```
./configure --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
```
I just exceuted the configure.How did you know about the prefix flag?

**Comment by MrSSHH** [comment]
I've used gtksourceviewmm a couple of times before so I recalled it's an option I'm not quite sure if it's on this version.

**Comment by Lea3D** [comment]
> Build gtksourceviewmm-3.0 yourself, it should help
> 
> wget https://download.gnome.org/sources/gtksourceviewmm/3.0/gtksourceviewmm-3.0.0.tar.gz tar -xvzf gtksourceviewmm-3.0.0.tar.gz cd gtksourceviewmm-3.0.0 ./configure --prefix=/usr sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool make sudo make install
> 
> then repeat in installer.

❤️ Thanks

**Comment by Nikitf777** [comment]
Why is this issue closed while the bug is still there? The script is still trying to install a package, which doesn't exist in repos.

**Comment by argenestel** [comment]
for temporary fix i did 

https://github.com/NanoMichael/MicroTeX/tree/flutter-support fork this and change the CMakelist.txt to gtksourceviewmm-4.0
then updated the pkg build and installed the 
https://github.com/end-4/dots-hyprland/blob/main/arch-packages/illogical-impulse-microtex-git/PKGBUILD

this separately

**Comment by cgyit** [comment]
> 对于临时修复 https://github.com/NanoMichael/MicroTeX/tree/flutter-support 我确实分叉了它并将CMakelist.txt更改为 gtksourceviewmm-4.0，然后更新了 PKG 构建并安装了 https://github.com/end-4/dots-hyprland/blob/main/arch-packages/illogical-impulse-microtex-git/PKGBUILD

oh,thanks!it worked.

**Comment by maxz255** [comment]
modify ~/.cache/dots-hyprland/arch-packages/illogical-impulse-microtex-git/PKGBUILD:
`
prepare() {
    cd $_pkgname
    sed -i 's/gtksourceviewmm-3.0/gtksourceviewmm-4.0/' CMakeLists.txt
}
`
it works for me

**Comment by cgyit** [comment]
> modify `~/.cache/dots-hyprland/arch-packages/illogical-impulse-microtex-git/PKGBUILD` add this snippets before `build()`
> 
> ```
> prepare() {
>     cd $_pkgname
>     sed -i 's/gtksourceviewmm-3.0/gtksourceviewmm-4.0/' CMakeLists.txt
> }
> ```
> 
> it works for me.

it works better 👍 👍 👍

**Comment by clsty** [comment]
> modify `~/.cache/dots-hyprland/arch-packages/illogical-impulse-microtex-git/PKGBUILD` add this snippets before `build()`
> 
> ```
> prepare() {
>     cd $_pkgname
>     sed -i 's/gtksourceviewmm-3.0/gtksourceviewmm-4.0/' CMakeLists.txt
> }
> ```
> 
> it works for me.

Nice, I'll modify the PKGBUILD accordingly. Thank you.

**Comment by Varringard** [comment]
Thx
